# Despliegue automático de Lambda en AWS
name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: productivo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda function
        run: zip -r lambda_function.zip lambda_function.py

      - name: Verificar archivo ZIP
        run: ls -l lambda_function.zip

      - name: Deploy to AWS Lambda
        run: |
         aws lambda create-function \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --runtime python3.9 \
            --role arn:aws:iam::920373020136:role/Administratoraccesslambda::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_LAMBDA_ROLE }} \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://lambda_function.zip \
            --region ${{ secrets.AWS_REGION }}